#!/bin/bash

set -eo pipefail

SERVICE=sms-web

if hash buildkite-agent 2>/dev/null ; then
  echo '--- retrieving service file'
  buildkite-agent artifact download ${SERVICE}@.service .
fi

if [[ ! -e ${SERVICE}@.service ]]; then
  echo "${SERVICE}@.service file is missing. Run script/build to create it."
  exit 1
fi

echo "--- sending fleet service file"
fleetctl --strict-host-key-checking=false destroy ${SERVICE}@.service || true
fleetctl --strict-host-key-checking=false submit ${SERVICE}@.service

echo '--- (re-)starting fleet service instances'
for i in {1..3}; do
  fleetctl --strict-host-key-checking=false destroy ${SERVICE}@$i || true
  fleetctl --strict-host-key-checking=false start ${SERVICE}@$i
  # TODO: Use consul to see if ${SERVICE}@$i is healthy yet before moving on
done
